# Generated by Django 5.1.4 on 2025-01-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='comment',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
